tap "homebrew/bundle"

brew "go"
brew "fish"
brew "tree"
brew "lazygit"
brew "fnm"
brew "watchman"
brew "stow"
brew "helix"

brew "typescript-language-server"
brew "tailwindcss-language-server"
brew "vscode-langservers-extracted"
brew "marksman"

cask "discord"
cask "visual-studio-code"
cask "docker"
cask "wezterm"
